image:
  name: "alpine/terragrunt:0.13.5"
  entrypoint: ["/bin/sh", "-c"]

variables:
  AWS_ACCESS_KEY_ID: "access key"
  AWS_SECRET_ACCESS_KEY: "secret key"
  AWS_DEFAULT_REGION: "ap-east-1"
  BASE_URL: https://raw.githubusercontent.com/LarvataTW/gitlab-terraform-pipeline/master/
  TF_PLAN: "$CI_PROJECT_DIR/gitlab-tfplan"
  TF_IN_AUTOMATION: "true"
  TF_TERRAGRUNT_ENABLED: "false"

stages:
  - check
  - deploy

before_script:
  - apk add bash curl git
  - curl $BASE_URL/gitlab-env.sh -o gitlab-env.sh
  - source gitlab-env.sh
  - |
    if [ $TF_TERRAGRUNT_ENABLED == "true" ];
    then
      export TERRAFORM=terragrunt
    else
      export TERRAFORM=terraform
    fi

    if [ "$WORK_DIR" != "" ];
    then
      cd $WORK_DIR;
      $TERRAFORM init -input=false
    fi

plan:
  stage: check
  only:
    - master
    - develop
  script:
    - |
      if [ "$WORK_DIR" != "" ];
      then
        git show;
        $TERRAFORM plan -out=$TF_PLAN -input=false;
      fi
  artifacts:
    paths:
      - "$TF_PLAN"
    expire_in: '3 days'

apply:
  stage: deploy
  when: manual
  only:
    - master
    - develop
  script:
    - |
      if [ -f $TF_PLAN ];
      then
        $TERRAFORM apply -input=false $TF_PLAN;
        $TERRAFORM show;
        $TERRAFORM output
      fi
  dependencies:
    - plan
