image:
  name: "hashicorp/terraform:0.12.28"
  entrypoint: ["/bin/sh", "-c"]

variables:
  AWS_ACCESS_KEY_ID: "access key"
  AWS_SECRET_ACCESS_KEY: "secret key"
  AWS_DEFAULT_REGION: "ap-east-1"
  BASE_URL: https://raw.githubusercontent.com/LarvataTW/gitlab-terraform-pipeline/develop
  TF_PLAN: "$CI_PROJECT_DIR/gitlab-tfplan"
  TF_IN_AUTOMATION: "true"

stages:
  - check
  - deploy

before_script:
  - apk add bash curl git
  - curl $BASE_URL/gitlab-env.sh -o gitlab-env.sh
  - source gitlab-env.sh
  - |
    if [ "$WORK_DIR" != "" ];
    then
      cd $WORK_DIR;
      terragrunt init -input=false
    fi

plan:
  stage: check
  only:
    - develop
  script:
    - |
      if [ "$WORK_DIR" != "" ];
      then
        git show;
        terragrunt plan -out=$TF_PLAN -input=false;
      fi
  artifacts:
    paths:
      - "$TF_PLAN"
    expire_in: '3 days'

apply:
  stage: deploy
  when: manual
  only:
    - develop
  script:
    - |
      if [ -f $TF_PLAN ];
      then
        terragrunt apply -input=false $TF_PLAN;
        terragrunt show;
        terragrunt output
      fi
  dependencies:
    - plan
