image:
  name: "hashicorp/terraform:0.12.24"
  entrypoint: ["/bin/sh", "-c"]

variables:
  AWS_ACCESS_KEY_ID: "access key"
  AWS_SECRET_ACCESS_KEY: "secret key"
  AWS_DEFAULT_REGION: "ap-northeast-1"
  BASE_URL: https://raw.githubusercontent.com/LarvataTW/gitlab-terraform-pipeline/master
  TF_PLAN: "$CI_PROJECT_DIR/gitlab-tfplan"
  TF_IN_AUTOMATION: true

stages:
  - check
  - deploy

before_script:
  - apk add bash curl
  - curl $BASE_URL/gitlab-env.sh -o gitlab-env.sh
  - source gitlab-env.sh
  - |
    if [ "$WORK_DIR" != "" ];
    then
      cd $WORK_DIR;
      terraform init -input=false
    fi

plan:
  stage: check
  script:
    - |
      if [ "$WORK_DIR" != "" ];
      then
        terraform show;
        terraform plan -out=$TF_PLAN -input=false;
      fi
  artifacts:
    paths:
      - "$TF_PLAN"
    expire_in: '3 days'

apply:
  stage: deploy
  when: manual
  only:
    refs:
      - master
  script:
    - |
      if [ -f $TF_PLAN ];
      then
        terraform apply -input=false $TF_PLAN
      fi
  dependencies:
    - plan
